Add simple implementation of animated starting badges to increase int…
eXa-online/lovemathe pull request #4
Opened 2022-01-14 19:34 UTC by Checkl

…eraction

2022-01-19 14:59 UTC, rm-- requested changes
Please rebase and squash all commits into a single one.

2022-01-19 14:59 UTC, rm-- commented on src/store/index.js
> +
Please remove this empty line.

2022-01-19 14:59 UTC, rm-- commented on src/store/index.js
> +            console.log("Ich werde aufgerufen", nextGameIndex)
Please remove this console statement.

2022-01-19 14:59 UTC, rm-- commented on src/store/index.js
> +            let initialBadge = state.gameOrder[0];
What do you think about adding a `firstGame` parameter instead of `initialBadge`?
This first game should also be added to `state.activeGames`.

2022-01-19 14:59 UTC, rm-- commented on src/components/OverallBadge.vue
> +  pointer-events: all;
Do we need this?

2022-01-20 08:27 UTC, Checkl commented on src/components/OverallBadge.vue
> +  pointer-events: all;
Removed unnecessary pointer-events attribute

2022-01-20 08:30 UTC, Checkl commented on src/store/index.js
> +            let initialBadge = state.gameOrder[0];
I replaced initialBadge with firstGame

2022-01-20 14:13 UTC, merged